import React, {useMemo} from 'react';
import {
  AbsoluteFill,
  Audio,
  Easing,
  Sequence,
  interpolate,
  staticFile,
  useCurrentFrame,
  useVideoConfig,
} from 'remotion';
import {FPS, getSegments, getVoiceover, type SolarCue, type SolarLocale} from './cues';
import {fontFamilyForLocale} from './fonts';
import {SolarScene} from './SolarScene';

/** One cue overlay. Mirrors the GSAP enter/exit from solar-composition.js:
 * enter over min(0.35s, visible/3) with power3.out, exit over
 * min(0.16s, visible/4) with power2.in — here as interpolate() with
 * cubic-out / quad-in, precomputed from the cue's own timestamps. */
const CueOverlay: React.FC<{cue: SolarCue}> = ({cue}) => {
  const frame = useCurrentFrame();
  const duration = Math.max(1, Math.round((cue.end - cue.start) * FPS));
  const visible = Math.max(0.12, cue.end - cue.start);
  const enterFrames = Math.max(1, Math.round(Math.min(0.35, visible / 3) * FPS));
  const exitFrames = Math.max(1, Math.round(Math.min(0.16, visible / 4) * FPS));
  const exiting = frame >= duration - exitFrames;

  const opacity = Math.min(
    interpolate(frame, [0, enterFrames], [0, 1], {
      easing: Easing.out(Easing.cubic),
      extrapolateLeft: 'clamp',
      extrapolateRight: 'clamp',
    }),
    interpolate(frame, [duration - exitFrames, duration], [1, 0], {
      easing: Easing.in(Easing.quad),
      extrapolateLeft: 'clamp',
      extrapolateRight: 'clamp',
    }),
  );
  const y = exiting
    ? interpolate(frame, [duration - exitFrames, duration], [0, -12], {
        easing: Easing.in(Easing.quad),
        extrapolateLeft: 'clamp',
        extrapolateRight: 'clamp',
      })
    : interpolate(frame, [0, enterFrames], [24, 0], {
        easing: Easing.out(Easing.cubic),
        extrapolateLeft: 'clamp',
        extrapolateRight: 'clamp',
      });

  return (
    <AbsoluteFill style={{opacity, transform: `translateY(${y}px)`}}>
      <div
        style={{
          position: 'absolute',
          top: 40,
          left: '50%',
          transform: 'translateX(-50%)',
          color: '#ffcc00',
          fontSize: 48,
          fontWeight: 'bold',
          textShadow: '0 2px 15px rgba(255,204,0,0.5)',
          whiteSpace: 'nowrap',
        }}
      >
        {cue.name}
      </div>
      <div
        style={{
          position: 'absolute',
          bottom: 200,
          left: '50%',
          transform: 'translateX(-50%)',
          width: 900,
          textAlign: 'center',
          color: '#fff',
          fontSize: 32,
          lineHeight: 1.5,
          textShadow: '0 2px 10px rgba(0,0,0,0.8)',
        }}
      >
        {cue.text}
      </div>
    </AbsoluteFill>
  );
};

export const Solar: React.FC<{locale: SolarLocale}> = ({locale}) => {
  const frame = useCurrentFrame();
  const {durationInFrames: totalFrames} = useVideoConfig();
  const voiceover = getVoiceover(locale);
  const segments = useMemo(() => getSegments(locale), [locale]);

  return (
    <AbsoluteFill style={{backgroundColor: '#02040b', fontFamily: fontFamilyForLocale(locale)}}>
      <SolarScene frame={frame} totalFrames={totalFrames} segments={segments} />
      {voiceover.cues.map((cue) => (
        <Sequence
          key={cue.id}
          name={cue.id}
          from={Math.round(cue.start * FPS)}
          durationInFrames={Math.max(1, Math.round((cue.end - cue.start) * FPS))}
        >
          <CueOverlay cue={cue} />
        </Sequence>
      ))}
      {/* Generated by `npm run voiceover`; not committed. */}
      <Audio src={staticFile(`voiceover/solar-system-${locale}.mp3`)} />
    </AbsoluteFill>
  );
};
