import React from 'react';
import {AbsoluteFill, Audio, Easing, interpolate, Sequence, staticFile, useCurrentFrame} from 'remotion';
import {CITIES, SCHOOLS, School} from './data';
import {SCENES} from './timing';

const C = {bg:'#071B2D', panel:'#0F3D56', cyan:'#19C3B1', gold:'#F4B942', white:'#F4F7F8', muted:'#A7C0C8'};
const font = {fontFamily:'Arial, "PingFang SC", "Microsoft YaHei", sans-serif'};
const tOf = (id: string) => SCENES.find((s)=>s.id===id)!;
const fade = (frame:number, start:number, length=18) => interpolate(frame,[start,start+length],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp',easing:Easing.out(Easing.cubic)});

const Background: React.FC = () => <AbsoluteFill style={{background:C.bg, ...font}}><div style={{position:'absolute',inset:0,opacity:.15,backgroundImage:`linear-gradient(rgba(25,195,177,.32) 1px,transparent 1px),linear-gradient(90deg,rgba(25,195,177,.32) 1px,transparent 1px)`,backgroundSize:'54px 54px'}}/><div style={{position:'absolute',left:-180,top:420,width:1100,height:1100,border:'2px solid rgba(25,195,177,.18)',borderRadius:'50%'}}/></AbsoluteFill>;

const Map: React.FC<{active?: string; zoom?: number}> = ({active, zoom=1}) => <div style={{position:'relative',width:850,height:730,transform:`scale(${zoom})`,transformOrigin:'center'}}>
  <svg viewBox="0 0 100 90" width="850" height="730" style={{position:'absolute',inset:0,filter:'drop-shadow(0 24px 28px rgba(0,0,0,.3))'}}>
    <path d="M8 36 L18 22 L36 16 L51 7 L68 11 L82 6 L96 20 L90 32 L98 42 L88 52 L78 60 L69 78 L51 84 L40 74 L26 79 L20 65 L9 57 Z" fill={C.panel} stroke={C.cyan} strokeWidth=".8"/>
    <path d="M14 40 Q48 26 89 24 M22 64 Q45 47 83 46 M39 15 Q49 40 69 77" fill="none" stroke="rgba(25,195,177,.35)" strokeWidth=".35"/>
  </svg>
  {CITIES.map((c)=><div key={c.name} style={{position:'absolute',left:`${c.x}%`,top:`${c.y}%`,transform:'translate(-50%,-50%)',display:'flex',flexDirection:'column',alignItems:'center',opacity:active===undefined||active===c.name?1:.34}}><div style={{width:active===c.name?24:12,height:active===c.name?24:12,borderRadius:'50% 50% 50% 0',transform:'rotate(-45deg)',background:active===c.name?C.gold:C.cyan,boxShadow:active===c.name?`0 0 0 12px rgba(244,185,66,.15)`:'none'}}/><span style={{marginTop:10,fontSize:active===c.name?25:18,color:active===c.name?C.white:C.muted,fontWeight:active===c.name?800:500,whiteSpace:'nowrap'}}>{c.name}</span></div>)}
</div>;

const Scene: React.FC<{id:string; children:React.ReactNode}> = ({id,children}) => { const f=useCurrentFrame(); return <AbsoluteFill style={{opacity:fade(f,0),padding:'100px 72px',justifyContent:'center',color:C.white,...font}}>{children}</AbsoluteFill>; };
const Header: React.FC<{text:string; index?:string}> = ({text,index}) => <div style={{position:'absolute',top:76,left:72,right:72,display:'flex',justifyContent:'space-between',alignItems:'center'}}><span style={{fontSize:24,letterSpacing:5,color:C.cyan,fontWeight:800}}>{text}</span>{index&&<span style={{fontSize:24,letterSpacing:3,color:C.gold}}>{index}</span>}</div>;

const Intro: React.FC = () => <Scene id="intro"><Header text="SHANDONG · UNDERGRADUATE ATLAS"/><div style={{fontSize:118,fontWeight:900,lineHeight:1.05,letterSpacing:-5}}>山东各地<br/>本科院校</div><div style={{width:260,height:8,background:C.gold,marginTop:38}}/><div style={{fontSize:34,lineHeight:1.55,color:C.muted,marginTop:38}}>全省地图快速切换<br/>5 所本科院校重点认识</div><div style={{position:'absolute',right:55,bottom:160,transform:'rotate(9deg)',opacity:.95}}><Map/></div></Scene>;

const Cities: React.FC = () => { const f=useCurrentFrame(); const local=Math.max(0,f); const active=CITIES[Math.max(0,Math.min(CITIES.length-1,Math.floor(local/14)))].name; return <Scene id="cities"><Header text="全省速览" index="16 地市"/><div style={{fontSize:54,fontWeight:800}}>从鲁西南到胶东沿海</div><div style={{fontSize:27,color:C.muted}}>地图节点按城市快速切换，先建立山东本科院校的地域坐标。</div><div style={{marginTop:30,alignSelf:'center'}}><Map active={active} zoom={.98}/></div><div style={{position:'absolute',left:72,bottom:90,fontSize:21,color:C.muted,letterSpacing:2}}>济南 · 青岛 · 淄博 · 枣庄 · 东营 · 烟台 · 潍坊 · 济宁 · 泰安 · 威海 · 日照 · 临沂 · 德州 · 聊城 · 滨州 · 菏泽</div></Scene>; };

const SchoolScene: React.FC<{id:string; school:School; index:number}> = ({id,school,index}) => { const f=useCurrentFrame(); const local=f; const a=fade(local,0); const b=fade(local,10); return <Scene id={id}><Header text="院校节点" index={`${String(index).padStart(2,'0')} / 05`}/><div style={{display:'flex',flexDirection:'column',gap:24,width:'100%',opacity:a,transform:`translateY(${(1-a)*24}px)`}}><div style={{display:'inline-flex',alignSelf:'flex-start',padding:'13px 22px',border:`2px solid ${C.cyan}`,color:C.cyan,fontSize:25,fontWeight:800}}>{school.city} · 本科院校</div><div style={{fontSize:28,color:C.gold,letterSpacing:2,fontWeight:800}}>{school.type}</div><div style={{fontSize:69,fontWeight:900,lineHeight:1.1,letterSpacing:-3}}>{school.name}</div><div style={{fontSize:32,color:C.muted,lineHeight:1.5,maxWidth:850}}>{school.desc}</div><div style={{display:'flex',gap:16,marginTop:14}}><div style={{padding:'18px 24px',background:'rgba(15,61,86,.86)',borderLeft:`6px solid ${C.cyan}`,fontSize:27,fontWeight:800}}>{school.tag}</div><div style={{padding:'18px 24px',background:'rgba(15,61,86,.56)',fontSize:25,color:C.muted}}>快速了解，不做院校排名</div></div></div><div style={{position:'absolute',right:30,bottom:120,opacity:b,transform:`scale(${.82+.18*b})`}}><Map active={school.city} zoom={.74}/></div><div style={{position:'absolute',bottom:50,left:72,fontSize:19,color:'rgba(167,192,200,.75)'}}>资料以学校官网与当年招生章程为准</div></Scene>; };

const Outro: React.FC = () => <Scene id="outro"><Header text="NEXT STEP"/><div style={{fontSize:72,fontWeight:900,lineHeight:1.1}}>先看方向，<br/>再看城市</div><div style={{width:260,height:8,background:C.gold,marginTop:36}}/><div style={{fontSize:31,lineHeight:1.55,color:C.muted,maxWidth:850,marginTop:34}}>山东本科院校选择，可以从学科方向、培养层次、城市与生活开始。具体招生计划，请核对当年官方章程。</div><div style={{fontSize:24,color:C.cyan,letterSpacing:3,marginTop:40}}>山东 · 本科院校地图速览</div></Scene>;

export const ShandongAtlas: React.FC = () => <AbsoluteFill><Background/><Sequence from={Math.round(tOf('intro').start*30)} durationInFrames={Math.round(tOf('intro').duration*30)}><Intro/></Sequence><Sequence from={Math.round(tOf('cities').start*30)} durationInFrames={Math.round(tOf('cities').duration*30)}><Cities/></Sequence>{SCHOOLS.map((school,i)=>{const id=['sdu','ouc','upc','hit','sdut'][i]; return <Sequence key={school.name} from={Math.round(tOf(id).start*30)} durationInFrames={Math.round(tOf(id).duration*30)}><SchoolScene id={id} school={school} index={i+1}/></Sequence>;})}<Sequence from={Math.round(tOf('outro').start*30)} durationInFrames={Math.round(tOf('outro').duration*30)}><Outro/></Sequence><Audio src={staticFile('voiceover/narration.zh.mp3')} /></AbsoluteFill>;
