import React from 'react';
import {AbsoluteFill, Audio, Easing, interpolate, Sequence, staticFile, useCurrentFrame} from 'remotion';
import {CITIES, City} from './data';
import {SCENES} from './timing';

const C={bg:'#071B2D',panel:'#0F3D56',cyan:'#19C3B1',gold:'#F4B942',white:'#F4F7F8',muted:'#A7C0C8'};
const font={fontFamily:'Arial, "PingFang SC", "Microsoft YaHei", sans-serif'};
const scene=(id:string)=>SCENES.find((s)=>s.id===id)!;
const fade=(frame:number, length=18)=>interpolate(frame,[0,length],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp',easing:Easing.out(Easing.cubic)});

const Background:React.FC=()=> <AbsoluteFill style={{background:C.bg,...font}}><div style={{position:'absolute',inset:0,opacity:.15,backgroundImage:`linear-gradient(rgba(25,195,177,.32) 1px,transparent 1px),linear-gradient(90deg,rgba(25,195,177,.32) 1px,transparent 1px)`,backgroundSize:'54px 54px'}}/><div style={{position:'absolute',left:-180,top:420,width:1100,height:1100,border:'2px solid rgba(25,195,177,.18)',borderRadius:'50%'}}/></AbsoluteFill>;

const Map:React.FC<{active?:string}> = ({active})=><div style={{position:'relative',width:820,height:650}}><svg viewBox="0 0 100 90" width="820" height="650" style={{position:'absolute',inset:0,filter:'drop-shadow(0 24px 28px rgba(0,0,0,.3))'}}><path d="M8 36 L18 22 L36 16 L51 7 L68 11 L82 6 L96 20 L90 32 L98 42 L88 52 L78 60 L69 78 L51 84 L40 74 L26 79 L20 65 L9 57 Z" fill={C.panel} stroke={C.cyan} strokeWidth=".8"/><path d="M14 40 Q48 26 89 24 M22 64 Q45 47 83 46 M39 15 Q49 40 69 77" fill="none" stroke="rgba(25,195,177,.35)" strokeWidth=".35"/></svg>{CITIES.map(c=><div key={c.name} style={{position:'absolute',left:`${c.x}%`,top:`${c.y}%`,transform:'translate(-50%,-50%)',display:'flex',flexDirection:'column',alignItems:'center',opacity:active===undefined||active===c.name?1:.3}}><div style={{width:active===c.name?24:11,height:active===c.name?24:11,borderRadius:'50% 50% 50% 0',transform:'rotate(-45deg)',background:active===c.name?C.gold:C.cyan,boxShadow:active===c.name?'0 0 0 12px rgba(244,185,66,.15)':'none'}}/><span style={{marginTop:9,fontSize:active===c.name?24:17,color:active===c.name?C.white:C.muted,fontWeight:active===c.name?800:500,whiteSpace:'nowrap'}}>{c.name}</span></div>)}</div>;

const Scene:React.FC<{id:string;children:React.ReactNode}>=({id,children})=>{const f=useCurrentFrame();return <AbsoluteFill style={{opacity:fade(f),padding:'92px 72px',justifyContent:'center',color:C.white,...font}}>{children}</AbsoluteFill>};
const Header:React.FC<{text:string;index?:string}>=({text,index})=><div style={{position:'absolute',top:70,left:72,right:72,display:'flex',justifyContent:'space-between',alignItems:'center'}}><span style={{fontSize:23,letterSpacing:4,color:C.cyan,fontWeight:800}}>{text}</span>{index&&<span style={{fontSize:23,letterSpacing:3,color:C.gold}}>{index}</span>}</div>;

const Intro:React.FC=()=> <Scene id="intro"><Header text="SHANDONG · UNIVERSITY ATLAS"/><div style={{fontSize:116,fontWeight:900,lineHeight:1.06,letterSpacing:-5}}>山东各地<br/>重点本科院校</div><div style={{width:270,height:8,background:C.gold,marginTop:34}}/><div style={{fontSize:32,lineHeight:1.55,color:C.muted,marginTop:34}}>16 个地市快速盘点<br/>每个地区最多 5 所代表性院校</div><div style={{position:'absolute',right:30,bottom:125,opacity:.92}}><Map/></div></Scene>;

const Overview:React.FC=()=> <Scene id="overview"><Header text="全省总览" index="16 地市"/><div style={{fontSize:50,fontWeight:800}}>从鲁西南到胶东沿海</div><div style={{fontSize:27,color:C.muted,marginTop:18}}>先看分布，再看院校。接下来按地市快速切换。</div><div style={{alignSelf:'center',marginTop:24}}><Map/></div><div style={{position:'absolute',left:72,bottom:72,fontSize:19,color:C.muted,letterSpacing:1}}>代表性本科院校 · 非官方排名 · 具体招生以当年章程为准</div></Scene>;

const CityScene:React.FC<{city:City;index:number}>=({city,index})=>{const f=useCurrentFrame();const a=fade(f);const b=fade(f,24);return <Scene id={city.name}><Header text="地市速览" index={`${String(index).padStart(2,'0')} / 16`}/><div style={{display:'flex',flexDirection:'column',gap:18,width:'100%',opacity:a,transform:`translateY(${(1-a)*22}px)`}}><div style={{display:'inline-flex',alignSelf:'flex-start',padding:'12px 20px',border:`2px solid ${C.cyan}`,color:C.cyan,fontSize:25,fontWeight:800}}>{city.name} · 本科院校</div><div style={{fontSize:23,color:C.gold,letterSpacing:2,fontWeight:800}}>代表性重点院校（非排名）</div><div style={{fontSize:62,fontWeight:900,lineHeight:1.08}}>{city.name}</div><div style={{display:'flex',flexDirection:'column',gap:10,marginTop:10,maxWidth:850}}>{city.schools.map((school,i)=><div key={school} style={{display:'flex',alignItems:'center',gap:14,padding:'12px 18px',background:i===0?'rgba(15,61,86,.9)':'rgba(15,61,86,.55)',borderLeft:`5px solid ${i===0?C.gold:C.cyan}`,fontSize:28,fontWeight:i===0?800:600}}><span style={{color:C.gold,fontSize:20}}>{String(i+1).padStart(2,'0')}</span>{school}</div>)}</div></div><div style={{position:'absolute',right:15,bottom:70,opacity:b,transform:`scale(${.72+.28*b})`}}><Map active={city.name}/></div></Scene>};

const Outro:React.FC=()=> <Scene id="outro"><Header text="END CARD"/><div style={{fontSize:70,fontWeight:900,lineHeight:1.12}}>一张地图，<br/>看懂山东本科版图</div><div style={{width:270,height:8,background:C.gold,marginTop:34}}/><div style={{fontSize:30,lineHeight:1.55,color:C.muted,maxWidth:850,marginTop:30}}>本片按地市盘点代表性本科院校，不构成院校排名或志愿建议。报考前请核对当年官方招生章程。</div></Scene>;

export const ShandongAtlas:React.FC=()=> <AbsoluteFill><Background/><Sequence from={Math.round(scene('intro').start*30)} durationInFrames={Math.round(scene('intro').duration*30)}><Intro/></Sequence><Sequence from={Math.round(scene('overview').start*30)} durationInFrames={Math.round(scene('overview').duration*30)}><Overview/></Sequence>{CITIES.map((city,i)=><Sequence key={city.name} from={Math.round(scene(city.name).start*30)} durationInFrames={Math.round(scene(city.name).duration*30)}><CityScene city={city} index={i+1}/></Sequence>)}<Sequence from={Math.round(scene('outro').start*30)} durationInFrames={Math.round(scene('outro').duration*30)}><Outro/></Sequence><Audio src={staticFile('voiceover/narration.zh.mp3')}/></AbsoluteFill>;
