export type University = {
  rank: number;
  name: string;
  nameEn: string;
  country: string;
  score: number;
};

export const PER_PAGE = 10;

export const UNIVERSITIES: University[] = [
  { rank: 1, name: '麻省理工学院', nameEn: 'Massachusetts Institute of Technology (MIT)', country: '美国', score: 100 },
  { rank: 2, name: '帝国理工学院', nameEn: 'Imperial College London', country: '英国', score: 99.2 },
  { rank: 2, name: '斯坦福大学', nameEn: 'Stanford University', country: '美国', score: 99.2 },
  { rank: 4, name: '牛津大学', nameEn: 'University of Oxford', country: '英国', score: 98.6 },
  { rank: 5, name: '哈佛大学', nameEn: 'Harvard University', country: '美国', score: 97.4 },
  { rank: 6, name: '剑桥大学', nameEn: 'University of Cambridge', country: '英国', score: 97.1 },
  { rank: 7, name: '加州理工学院', nameEn: 'California Institute of Technology (Caltech)', country: '美国', score: 96.6 },
  { rank: 8, name: '苏黎世联邦理工学院', nameEn: 'ETH Zurich', country: '瑞士', score: 96.3 },
  { rank: 8, name: '伦敦大学学院', nameEn: 'UCL', country: '英国', score: 96.3 },
  { rank: 10, name: '新加坡国立大学', nameEn: 'National University of Singapore (NUS)', country: '新加坡', score: 96.2 },
  { rank: 11, name: '香港大学', nameEn: 'The University of Hong Kong', country: '中国香港', score: 95.9 },
  { rank: 12, name: '南洋理工大学', nameEn: 'Nanyang Technological University, Singapore (NTU Singapore)', country: '新加坡', score: 93.6 },
  { rank: 13, name: '北京大学', nameEn: 'Peking University', country: '中国', score: 92.6 },
  { rank: 14, name: '清华大学', nameEn: 'Tsinghua University', country: '中国', score: 92.1 },
  { rank: 15, name: '宾夕法尼亚大学', nameEn: 'University of Pennsylvania', country: '美国', score: 91.7 },
  { rank: 16, name: '康奈尔大学', nameEn: 'Cornell University', country: '美国', score: 91.5 },
  { rank: 16, name: '耶鲁大学', nameEn: 'Yale University', country: '美国', score: 91.5 },
  { rank: 18, name: '香港中文大学', nameEn: 'The Chinese University of Hong Kong (CUHK)', country: '中国香港', score: 89.9 },
  { rank: 19, name: '新南威尔士大学', nameEn: 'The University of New South Wales (UNSW Sydney)', country: '澳大利亚', score: 89.8 },
  { rank: 20, name: '约翰霍普金斯大学', nameEn: 'Johns Hopkins University', country: '美国', score: 89.7 },
  { rank: 20, name: '加州大学伯克利分校', nameEn: 'University of California, Berkeley (UCB)', country: '美国', score: 89.7 },
  { rank: 22, name: '洛桑联邦理工学院', nameEn: 'EPFL – École polytechnique fédérale de Lausanne', country: '瑞士', score: 89.6 },
  { rank: 22, name: '墨尔本大学', nameEn: 'The University of Melbourne', country: '澳大利亚', score: 89.6 },
  { rank: 24, name: '芝加哥大学', nameEn: 'University of Chicago', country: '美国', score: 89.2 },
  { rank: 25, name: '慕尼黑工业大学', nameEn: 'Technical University of Munich', country: '德国', score: 89.1 },
  { rank: 26, name: '复旦大学', nameEn: 'Fudan University', country: '中国', score: 89 },
  { rank: 27, name: '普林斯顿大学', nameEn: 'Princeton University', country: '美国', score: 88.9 },
  { rank: 28, name: '悉尼大学', nameEn: 'The University of Sydney', country: '澳大利亚', score: 88.4 },
  { rank: 29, name: '澳大利亚国立大学', nameEn: 'Australian National University (ANU)', country: '澳大利亚', score: 87.6 },
  { rank: 30, name: '麦吉尔大学', nameEn: 'McGill University', country: '加拿大', score: 87.5 },
  { rank: 31, name: '蒙纳士大学', nameEn: 'Monash University', country: '澳大利亚', score: 87 },
  { rank: 32, name: '多伦多大学', nameEn: 'University of Toronto', country: '加拿大', score: 86.8 },
  { rank: 33, name: '香港科技大学', nameEn: 'The Hong Kong University of Science and Technology', country: '中国香港', score: 86.4 },
  { rank: 34, name: '巴黎文理研究大学', nameEn: 'Université PSL', country: '法国', score: 86 },
  { rank: 35, name: '爱丁堡大学', nameEn: 'The University of Edinburgh', country: '英国', score: 85.9 },
  { rank: 36, name: '上海交通大学', nameEn: 'Shanghai Jiao Tong University', country: '中国', score: 85.8 },
  { rank: 37, name: '伦敦国王学院', nameEn: "King's College London", country: '英国', score: 85.7 },
  { rank: 38, name: '首尔国立大学', nameEn: 'Seoul National University', country: '韩国', score: 85.4 },
  { rank: 39, name: '东京大学', nameEn: 'The University of Tokyo', country: '日本', score: 84.8 },
  { rank: 40, name: '曼彻斯特大学', nameEn: 'The University of Manchester', country: '英国', score: 84.6 },
  { rank: 40, name: '昆士兰大学', nameEn: 'The University of Queensland', country: '澳大利亚', score: 84.6 },
  { rank: 42, name: '延世大学', nameEn: 'Yonsei University', country: '韩国', score: 84.2 },
  { rank: 43, name: '哥伦比亚大学', nameEn: 'Columbia University', country: '美国', score: 84 },
  { rank: 43, name: '巴黎理工学院', nameEn: 'Institut Polytechnique de Paris', country: '法国', score: 84 },
  { rank: 45, name: '西北大学', nameEn: 'Northwestern University', country: '美国', score: 83.8 },
  { rank: 45, name: '不列颠哥伦比亚大学', nameEn: 'University of British Columbia', country: '加拿大', score: 83.9 },
  { rank: 47, name: '浙江大学', nameEn: 'Zhejiang University', country: '中国', score: 83.5 },
  { rank: 48, name: '代尔夫特理工大学', nameEn: 'Delft University of Technology', country: '荷兰', score: 83.1 },
  { rank: 49, name: '加州大学洛杉矶分校', nameEn: 'University of California, Los Angeles (UCLA)', country: '美国', score: 82.7 },
  { rank: 50, name: '香港理工大学', nameEn: 'The Hong Kong Polytechnic University', country: '中国香港', score: 82.3 },
  { rank: 51, name: '密歇根大学', nameEn: 'University of Michigan-Ann Arbor', country: '美国', score: 82.2 },
  { rank: 52, name: '香港城市大学', nameEn: 'City University of Hong Kong (CityUHK)', country: '中国香港', score: 81.9 },
  { rank: 52, name: '高丽大学', nameEn: 'Korea University', country: '韩国', score: 81.9 },
  { rank: 54, name: '台湾大学', nameEn: 'National Taiwan University (NTU)', country: '中国台湾', score: 81.7 },
  { rank: 55, name: '卡内基梅隆大学', nameEn: 'Carnegie Mellon University', country: '美国', score: 81.4 },
  { rank: 56, name: '马来亚大学', nameEn: 'Universiti Malaya (UM)', country: '马来西亚', score: 81.2 },
  { rank: 57, name: '布里斯托大学', nameEn: 'University of Bristol', country: '英国', score: 80.9 },
  { rank: 58, name: '纽约大学', nameEn: 'New York University (NYU)', country: '美国', score: 80.8 },
  { rank: 59, name: '鲁汶大学', nameEn: 'KU Leuven', country: '比利时', score: 80.5 },
  { rank: 60, name: '阿姆斯特丹大学', nameEn: 'University of Amsterdam', country: '荷兰', score: 80.2 },
  { rank: 61, name: '慕尼黑大学', nameEn: 'Ludwig-Maximilians-Universität München', country: '德国', score: 79.6 },
  { rank: 62, name: '伦敦政治经济学院', nameEn: 'The London School of Economics and Political Science (LSE)', country: '英国', score: 78.8 },
  { rank: 63, name: '法赫德国王石油矿产大学', nameEn: 'KFUPM', country: '沙特阿拉伯', score: 78.3 },
  { rank: 64, name: '京都大学', nameEn: 'Kyoto University', country: '日本', score: 78.2 },
  { rank: 65, name: '韩国科学技术院', nameEn: 'KAIST', country: '韩国', score: 77.7 },
  { rank: 66, name: '布朗大学', nameEn: 'Brown University', country: '美国', score: 77.4 },
  { rank: 67, name: '奥克兰大学', nameEn: 'The University of Auckland', country: '新西兰', score: 77 },
  { rank: 68, name: '华威大学', nameEn: 'University of Warwick', country: '英国', score: 75.9 },
  { rank: 68, name: '伯明翰大学', nameEn: 'University of Birmingham', country: '英国', score: 75.9 },
  { rank: 70, name: '杜克大学', nameEn: 'Duke University', country: '美国', score: 75.8 },
  { rank: 71, name: '隆德大学', nameEn: 'Lund University', country: '瑞典', score: 75.7 },
  { rank: 72, name: '德克萨斯大学奥斯汀分校', nameEn: 'University of Texas at Austin', country: '美国', score: 75.3 },
  { rank: 73, name: '索邦大学', nameEn: 'Sorbonne University', country: '法国', score: 74.8 },
  { rank: 74, name: '伊利诺伊大学香槟分校', nameEn: 'University of Illinois Urbana-Champaign', country: '美国', score: 74.7 },
  { rank: 75, name: '都柏林三一学院', nameEn: 'Trinity College Dublin, The University of Dublin', country: '爱尔兰', score: 74.4 },
  { rank: 76, name: '巴黎萨克雷大学', nameEn: 'Université Paris-Saclay', country: '法国', score: 73.8 },
  { rank: 77, name: '西澳大学', nameEn: 'The University of Western Australia', country: '澳大利亚', score: 73.7 },
  { rank: 77, name: '利兹大学', nameEn: 'University of Leeds', country: '英国', score: 73.7 },
  { rank: 79, name: '阿德莱德大学', nameEn: 'Adelaide University', country: '澳大利亚', score: 73.6 },
  { rank: 80, name: '格拉斯哥大学', nameEn: 'University of Glasgow', country: '英国', score: 73.4 },
  { rank: 81, name: '加州大学圣地亚哥分校', nameEn: 'University of California, San Diego (UCSD)', country: '美国', score: 73.3 },
  { rank: 82, name: '皇家理工学院', nameEn: 'KTH Royal Institute of Technology', country: '瑞典', score: 72.7 },
  { rank: 82, name: '谢菲尔德大学', nameEn: 'The University of Sheffield', country: '英国', score: 72.7 },
  { rank: 84, name: '布宜诺斯艾利斯大学', nameEn: 'Universidad de Buenos Aires (UBA)', country: '阿根廷', score: 72.3 },
  { rank: 85, name: '杜伦大学', nameEn: 'Durham University', country: '英国', score: 71.7 },
  { rank: 86, name: '海德堡大学', nameEn: 'Universität Heidelberg', country: '德国', score: 70.6 },
  { rank: 87, name: '米兰理工大学', nameEn: 'Politecnico di Milano', country: '意大利', score: 70.5 },
  { rank: 87, name: '悉尼科技大学', nameEn: 'The University of Technology Sydney (UTS)', country: '澳大利亚', score: 70.5 },
  { rank: 87, name: '乌普萨拉大学', nameEn: 'Uppsala University', country: '瑞典', score: 70.5 },
  { rank: 90, name: '南京大学', nameEn: 'Nanjing University', country: '中国', score: 70.4 },
  { rank: 90, name: '哥本哈根大学', nameEn: 'University of Copenhagen', country: '丹麦', score: 70.4 },
  { rank: 92, name: '宾夕法尼亚州立大学', nameEn: 'Pennsylvania State University', country: '美国', score: 70.2 },
  { rank: 92, name: '华盛顿大学', nameEn: 'University of Washington', country: '美国', score: 70.2 },
  { rank: 94, name: '波士顿大学', nameEn: 'Boston University', country: '美国', score: 70 },
  { rank: 95, name: '大阪大学', nameEn: 'The University of Osaka', country: '日本', score: 69.5 },
  { rank: 96, name: '阿尔伯塔大学', nameEn: 'University of Alberta', country: '加拿大', score: 69.3 },
  { rank: 97, name: '东京科学大学', nameEn: 'Institute of Science Tokyo', country: '日本', score: 69.2 },
  { rank: 97, name: '诺丁汉大学', nameEn: 'University of Nottingham', country: '英国', score: 69.2 },
  { rank: 98, name: '柏林自由大学', nameEn: 'Freie Universitaet Berlin', country: '德国', score: 69 },
  { rank: 98, name: '苏黎世大学', nameEn: 'University of Zurich', country: '瑞士', score: 69 },
];

export const PAGES: University[][] = Array.from(
  {length: Math.ceil(UNIVERSITIES.length / PER_PAGE)},
  (_, p) => UNIVERSITIES.slice(p * PER_PAGE, p * PER_PAGE + PER_PAGE),
);

export type PageAccent = {color: string; glow: string};

/** Per-page accent colors, mirroring the `.page-N` CSS variables in index.html. */
export const PAGE_COLORS: PageAccent[] = [
  {color: '#e94560', glow: 'rgba(233, 69, 96, 0.3)'},
  {color: '#3498db', glow: 'rgba(52, 152, 219, 0.3)'},
  {color: '#2ecc71', glow: 'rgba(46, 204, 113, 0.3)'},
  {color: '#f39c12', glow: 'rgba(243, 156, 18, 0.3)'},
  {color: '#9b59b6', glow: 'rgba(155, 89, 182, 0.3)'},
  {color: '#1abc9c', glow: 'rgba(26, 188, 156, 0.3)'},
  {color: '#e74c3c', glow: 'rgba(231, 76, 60, 0.3)'},
  {color: '#00bcd4', glow: 'rgba(0, 188, 212, 0.3)'},
  {color: '#ff9800', glow: 'rgba(255, 152, 0, 0.3)'},
  {color: '#8bc34a', glow: 'rgba(139, 195, 74, 0.3)'},
];
